server:
  port: 80
security:
  basic:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/activiti5?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 879411
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    prefix: classpath:/templates

#mybatis config
mybatis:
  mapper-locations: classpath:/mapper/*.xml